"""Build-time generator for a self-contained Model-Exchange FMU of a bond graph.

The problem with keeping the symbolic matrices + ``sympy.lambdify`` inside the
slave's ``__init__`` is that *all* of that code runs at FMU **instantiation**
time -- i.e. inside Simulink. That forces the Python interpreter Simulink picks
up to have ``sympy`` AND ``pyBondGraph`` (and their dependencies) importable,
which is fragile and hard to reproduce outside the development ``.venv``.

This module instead does *all* symbolic work here, at build time, and emits a
self-contained slave module (``fmu_slave.py``) whose only runtime imports are
the standard library (``math``) and ``pythonfmu3`` (which the FMU bundles its
own runtime for). No sympy, no pyBondGraph at runtime.

Parameters stay genuinely live: the generated matrix functions take the
parameters as arguments, and the slave re-evaluates them every derivative step
from the current parameter attributes. So changing a parameter from Simulink
still changes the dynamics -- nothing is baked in at export time.

Usage::

    python pyBondGraph/fmu_export.py        # writes fmu_slave.py and builds the FMU
"""

from pathlib import Path

import sympy as sp

from pyBondGraph import BondGraph, SourceEffort, Inductor, Resistor, OneJunction, Gyrator


# -----------------------------------------------------------------------------
# Model definition (the only hardcoded part)
# -----------------------------------------------------------------------------
def build_bond_graph() -> BondGraph:
    """Build and return the bond graph to be exported.

    Swap the body of this function to export a different model; everything
    downstream is fully generic.
    """
    bond_graph = BondGraph()

    voltage_source = SourceEffort("V", "U_in")
    junction_elec = OneJunction("J1_1")
    inductor = Inductor("I_elec", "L_A", numeric_value=15e-6)
    resistor = Resistor("R_elec", "R_A", numeric_value=4)
    gyrator = Gyrator("G1", "K_t", numeric_value=9.54e-3)
    junction_mech = OneJunction("J1_2")
    bearing = Resistor("R_mech", "R_B", numeric_value=1e-6)
    inertia = Inductor("I_mech", "J", numeric_value=1e-6)

    bond_graph.connect(voltage_source, junction_elec)
    bond_graph.connect(junction_elec, resistor)
    bond_graph.connect(junction_elec, inductor)
    bond_graph.connect(junction_elec, gyrator)
    bond_graph.connect(gyrator, junction_mech)
    bond_graph.connect(junction_mech, bearing)
    bond_graph.connect(junction_mech, inertia)

    return bond_graph


# -----------------------------------------------------------------------------
# Code generation
# -----------------------------------------------------------------------------
def _matrix_literal(M: sp.Matrix) -> str:
    """Render a sympy Matrix as a nested-list Python literal using pure math.

    ``sp.pycode`` emits plain arithmetic operators and ``math.``-qualified
    function calls, so the result evaluates with only the standard library.
    """
    if M.rows == 0 or M.cols == 0:
        return "[]"
    rows = []
    for i in range(M.rows):
        elems = [sp.pycode(M[i, j]) for j in range(M.cols)]
        rows.append("[" + ", ".join(elems) + "]")
    return "[" + ", ".join(rows) + "]"


def _matrix_fn_src(name: str, M: sp.Matrix, params) -> str:
    args = ", ".join(p.name for p in params)
    return f"def {name}({args}):\n    return {_matrix_literal(M)}\n"


def generate_slave_source(bond_graph: BondGraph, class_name: str = "BondGraphSlave") -> str:
    """Do all the symbolic work and return the source of a self-contained slave."""
    bond_graph.assign_causality()

    A, B, C, D, _x, n_states, n_inputs, n_outputs = bond_graph.get_state_space()
    n_bonds = len(bond_graph.bonds)

    # Free parameters = every symbol in A/B/C/D that is not an input.
    free_vars = set()
    for Mtx in (A, B, C, D):
        free_vars |= Mtx.free_symbols
    for inp in bond_graph.inputs:
        free_vars.discard(inp)
    params = sorted(free_vars, key=lambda s: s.name)

    subs = bond_graph.get_substitution_dict()

    state_names = [sv.name for sv in bond_graph.state_vars]
    input_names = [iv.name for iv in bond_graph.inputs]
    param_names = [p.name for p in params]
    param_starts = {p.name: float(subs.get(p, 0.0)) for p in params}

    matrix_fns = "\n".join(
        _matrix_fn_src(fn, Mtx, params)
        for fn, Mtx in (("_A_fn", A), ("_B_fn", B), ("_C_fn", C), ("_D_fn", D))
    )

    # ---- assemble the runtime module ---------------------------------------
    return f'''\
"""AUTO-GENERATED by fmu_export.py -- do not edit by hand.

Self-contained Model-Exchange FMU slave for a bond graph. Runtime dependencies:
only the standard library and pythonfmu3 (bundled into the FMU). No sympy, no
pyBondGraph. Parameters are live: the generated matrix functions take them as
arguments and are re-evaluated each step from the current parameter attributes.
"""

import math  # noqa: F401  (used by generated matrix expressions)
from typing import List

from pythonfmu3 import (
    Fmi3Causality,
    Fmi3SlaveBase,
    Fmi3Variability,
    Fmi3Initial,
    Float64,
    ModelExchange,
)

# ----- model metadata (precomputed at build time) ---------------------------
STATE_NAMES = {state_names!r}
INPUT_NAMES = {input_names!r}
PARAM_NAMES = {param_names!r}
PARAM_STARTS = {param_starts!r}
N_STATES = {n_states}
N_INPUTS = {n_inputs}
N_OUTPUTS = {n_outputs}
N_BONDS = {n_bonds}


# ----- generated state-space matrices (functions of the parameters) ---------
{matrix_fns}

_MATRIX_FNS = (_A_fn, _B_fn, _C_fn, _D_fn)


class {class_name}(Fmi3SlaveBase, ModelExchange):
    """Generic Model-Exchange FMU wrapper; all model data is generated above."""

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.author = "MtP"
        self.description = "Bondgraph test"

        self.n_states = N_STATES
        self.n_inputs = N_INPUTS
        self.n_outputs = N_OUTPUTS
        self.n_bonds = N_BONDS

        self._register_variables()

    # ------------------------------------------------------------------
    # Registration
    # ------------------------------------------------------------------
    def _make_var(self, name: str, start: float = 0.0, **kwargs) -> Float64:
        """Float64 with EXPLICIT getter/setter bound to an instance attribute.

        This bypasses pythonfmu3's fragile auto-setter logic, which only creates
        a setter when hasattr(self, name) is already True at registration time
        and uses a name demangled via lstrip('_'). Binding explicitly makes the
        order irrelevant and avoids the "'NoneType' object is not callable"
        crash in fmi3SetFloat64.
        """
        setattr(self, name, float(start))
        var = Float64(name, **kwargs)
        var.getter = (lambda n=name: getattr(self, n))
        var.setter = (lambda v, n=name: setattr(self, n, v))
        return var

    def _register_variables(self) -> None:
        self.register_variable(
            self._make_var(
                "time",
                causality=Fmi3Causality.independent,
                variability=Fmi3Variability.continuous,
            )
        )

        # States (outputs) + their derivatives (local). The FMI `derivative`
        # attribute must reference the value reference of the state it derives,
        # which register_variable assigns onto the variable object.
        for sname in STATE_NAMES:
            state = self._make_var(
                sname,
                causality=Fmi3Causality.output,
                start=0.0,
                variability=Fmi3Variability.continuous,
                initial=Fmi3Initial.exact,
            )
            self.register_variable(state)
            self.register_variable(
                self._make_var(
                    f"der_{{sname}}",
                    causality=Fmi3Causality.local,
                    variability=Fmi3Variability.continuous,
                    derivative=state.value_reference,
                )
            )

        # Inputs (sources).
        for iname in INPUT_NAMES:
            self.register_variable(
                self._make_var(
                    iname,
                    causality=Fmi3Causality.input,
                    variability=Fmi3Variability.continuous,
                    initial=Fmi3Initial.exact,
                )
            )

        # Outputs: effort of every bond, then flow of every bond.
        for i in range(self.n_bonds):
            self.register_variable(
                self._make_var(
                    f"e_{{i + 1}}",
                    causality=Fmi3Causality.output,
                    variability=Fmi3Variability.continuous,
                    initial=Fmi3Initial.exact,
                )
            )
        for i in range(self.n_bonds):
            self.register_variable(
                self._make_var(
                    f"f_{{i + 1}}",
                    causality=Fmi3Causality.output,
                    variability=Fmi3Variability.continuous,
                    initial=Fmi3Initial.exact,
                )
            )

        # Parameters: configurable from the outside (e.g. Simulink).
        for pname in PARAM_NAMES:
            self.register_variable(
                self._make_var(
                    pname,
                    start=PARAM_STARTS[pname],
                    causality=Fmi3Causality.parameter,
                    variability=Fmi3Variability.fixed,
                    initial=Fmi3Initial.exact,
                )
            )

    # ------------------------------------------------------------------
    # Runtime evaluation
    # ------------------------------------------------------------------
    @staticmethod
    def _mat_vec(M, x):
        """Matrix (nested list) times vector, pure python."""
        return [sum(M[i][j] * x[j] for j in range(len(x))) for i in range(len(M))]

    def _current_matrices(self):
        """Evaluate the generated state-space at the CURRENT parameter values."""
        p = [getattr(self, n) for n in PARAM_NAMES]
        return (fn(*p) for fn in _MATRIX_FNS)

    def _state_and_input_vectors(self):
        x = [getattr(self, n) for n in STATE_NAMES]
        u = [getattr(self, n) for n in INPUT_NAMES]
        return x, u

    def _update_outputs(self, C, D, x, u) -> None:
        """Compute y = C*x + D*u and write efforts/flows.

        y has length N_OUTPUTS = 2*N_BONDS: efforts occupy the first half of the
        rows, flows the second half, so the split point is N_OUTPUTS // 2.
        """
        Cx = self._mat_vec(C, x) if x else [0.0] * self.n_outputs
        Du = self._mat_vec(D, u) if u else [0.0] * self.n_outputs
        y = [Cx[i] + Du[i] for i in range(self.n_outputs)]

        stride = self.n_outputs // 2
        for i in range(stride):
            setattr(self, f"e_{{i + 1}}", y[i])
            setattr(self, f"f_{{i + 1}}", y[i + stride])

    def get_continuous_state_derivatives(self) -> List[float]:
        A, B, C, D = self._current_matrices()
        x, u = self._state_and_input_vectors()

        Ax = self._mat_vec(A, x) if x else [0.0] * self.n_states
        Bu = self._mat_vec(B, u) if u else [0.0] * self.n_states
        dx = [Ax[i] + Bu[i] for i in range(self.n_states)]

        for i, sname in enumerate(STATE_NAMES):
            setattr(self, f"der_{{sname}}", dx[i])

        self._update_outputs(C, D, x, u)
        return dx

'''


# -----------------------------------------------------------------------------
# Build entry point
# -----------------------------------------------------------------------------
if __name__ == "__main__":
    here = Path(__file__).resolve().parent
    slave_path = here / "fmu_slave.py"

    source = generate_slave_source(build_bond_graph())
    slave_path.write_text(source, encoding="utf-8")
    print(f"Generated self-contained slave: {slave_path}")

    # Build the FMU from the generated (dependency-free) slave module.
    from pythonfmu3 import FmuBuilder

    FmuBuilder.build_FMU(str(slave_path), dest=str(here.parent))
    print("FMU built.")

    slave_path.unlink()  # clean up the generated slave module
